### ISSUE TITLE
Cannot Install on laravel 8

### ISSUE THREAD

**Issue by sindhu13** [alfa6661/laravel-autonumber#10]
i have a problem...
i can't install this autonumber on laravel 8...
this is my composer.json:
![image](https://user-images.githubusercontent.com/2950240/153827787-debffebd-b452-42c9-974d-3f1630f4694a.png)

and this is the errors:
![image](https://user-images.githubusercontent.com/2950240/153828037-ada64052-fd42-4c94-b740-e8f0733195f2.png)

how i can fix it?
thank you

**Comment by alfa6661** [comment]
use version 1.2.5
