### ISSUE TITLE
bagaimana caranya membuat kode yang berbeda dalam 1 tabel?

### ISSUE THREAD

**Issue by abdulcrb** [alfa6661/laravel-autonumber#8]
terimakasih mas atas pembuatan paket autonumber.
saya ingin bertanya bagaimana di dalam 1 model ada autonubmer yang berbeda beda misal di dalam buku kas itu ata kas masuk sma keluar bisa tidak didalam 1 model ada 2 kode yang berbeda, cara paling gampang memang kita buat model masing masing.

terimakasih

**Comment by alfa6661** [comment]
```
/**
 * Return the autonumber configuration array for this model.
 *
 * @return array
 */
public function getAutoNumberOptions()
{
    return [
        'masuk' => [
            'format' => 'FORMAT.?',
            'length' => 5
        ],
        'keluar' => [
            'format' => 'FORMAT.?',
            'length' => 5
        ]
    ];
}
```
